name: 🔁 Auto Backup Chat Memory

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes
  workflow_dispatch:        # Allow manual run too

permissions:
  contents: write           # ✅ Needed to push commits

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: 🧠 Copy chat memory
        run: |
          mkdir -p backups
          cp chat-memory.json backups/chat-memory-$(date +'%Y%m%d-%H%M%S').json

      - name: 💾 Commit and push backup
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add backups/
          git commit -m "🧠 Auto-backup chat memory $(date)"
          git push
