name: 🟣 Auto Embed 8BFR Footer + Site Map

on:
  workflow_dispatch:

jobs:
  embed:
    runs-on: ubuntu-latest
    steps:
      - name: 🧩 Checkout repo
        uses: actions/checkout@v4

      - name: 🖋 Append 8BFR Footer + Site Map
        run: |
          FOOTER='
          <!-- 🟣 8BFR Dynamic Footer -->
          <footer style="text-align:center; padding:30px 10px; background:#100022; color:#ccc; border-top:1px solid #2b0050; box-shadow:0 -2px 8px rgba(160,32,240,0.3); font-family:Poppins, sans-serif;">
            <h2 style="color:#a020f0; text-shadow:0 0 8px #a020f0;">🎵 8BFR Music Network</h2>
            <p>Create • Connect • Collab</p>

            <div style="margin:20px auto; max-width:800px;">
              <details style="margin:10px 0;">
                <summary style="cursor:pointer; color:#a020f0; font-weight:bold;">🎶 Music</summary>
                <p>🏠 Home • 📻 Radio • 🎸 Artist-Studio • 🥁 Beats • 📚 Stories</p>
              </details>
              <details style="margin:10px 0;">
                <summary style="cursor:pointer; color:#a020f0; font-weight:bold;">🎮 Games</summary>
                <p>🎱 8BFR Game Hub • 🎱 8-Ball • 🎱 9-Ball • 🔥 Trickshot • 🎵 Game Music • 🎮 Arcade</p>
              </details>
              <details style="margin:10px 0;">
                <summary style="cursor:pointer; color:#a020f0; font-weight:bold;">👥 Community</summary>
                <p>💬 Chat • 🖥 Feed • 🥇 Contest • 👪 Kids Zone • 📚 Blog & Announcements</p>
              </details>
              <details style="margin:10px 0;">
                <summary style="cursor:pointer; color:#a020f0; font-weight:bold;">👔 Studios & Panels</summary>
                <p>👑 Owner • 📛 Admin • ⛔ Mod • 📜 Admin Guide • 🎸 Artist-Studio</p>
              </details>
              <details style="margin:10px 0;">
                <summary style="cursor:pointer; color:#a020f0; font-weight:bold;">💲 Info</summary>
                <p>💲 Pricing • 🔏 Privacy • 📃 Terms • 📊 Stats • ❔ FAQ • 🚫 Rules • 📨 Contact</p>
              </details>
            </div>

            <object data="https://8bfr.github.io/8bfr-Music-Network/assets/8bfr-site-map.svg"
                    type="image/svg+xml"
                    width="500" height="400"
                    style="filter: drop-shadow(0 0 10px #a020f0); animation:pulse 3s infinite;">
            </object>

            <p style="margin-top:20px; font-size:0.9em;">© 2025 8BFR Music Network | All Rights Reserved</p>
          </footer>

          <style>
            @keyframes pulse {
              0%,100% { filter: drop-shadow(0 0 8px #a020f0); }
              50% { filter: drop-shadow(0 0 20px #a020f0); }
            }
          </style>
          '

          for f in $(find . -maxdepth 1 -name "*.html"); do
            echo "Updating $f..."
            grep -q "</body>" "$f" && sed -i "/<\/body>/i $FOOTER" "$f" || echo "$FOOTER" >> "$f"
          done

      - name: 🚀 Commit and push changes
        run: |
          git config --global user.name "8BFR Bot"
          git config --global user.email "records.8bfr.music.network@gmail.com"
          git add .
          git commit -m "🟣 Auto-embedded 8BFR Footer + Site Map"
          git push https://x-access-token:${{ secrets.UPLOAD_TOKEN }}@github.com/8bfr/8bfr-Music-Network.git HEAD:main
