name: 🔁 Auto Backup Chat Memory

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: 🧠 Copy chat memory
        run: |
          mkdir -p backups
          cp chat-memory.json backups/chat-memory-$(date +'%Y%m%d-%H%M%S').json

      - name: 🧹 Delete backups older than 365 days
        run: |
          find backups/ -type f -name "*.json" -mtime +365 -exec rm {} \; || true

      - name: 💾 Commit and push backup
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add backups/
          git commit -m "🧠 Auto-backup chat memory $(date)" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF}

      - name: 📧 Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "🧠 8BFR Backup Status: ${{ job.status }}"
          to: "records.8bfr.music.network@gmail.com"
          from: "8BFR Backup Bot <records.8bfr.music.network@gmail.com>"
          body: |
            Backup Job: ${{ github.workflow }}
            Status: ${{ job.status }}
            Repository: ${{ github.repository }}
            Run ID: ${{ github.run_id }}
            Timestamp: $(date)
