- name: 📧 Send email notification
     if: always()
     uses: dawidd6/action-send-mail@v3
     with:
       server_address: smtp.sendgrid.net
       server_port: 587
       secure: false
       username: ${{ secrets.SENDGRID_USER }}
       password: ${{ secrets.SENDGRID_PASS }}
       subject: "🧠 8BFR Backup Status: ${{ job.status }}"
       to: "records.8bfr.music.network@gmail.com"
       from: "8BFR Backup Bot <records@8bfr.music.network>"
       body: |
         Backup Job: ${{ github.workflow }}
         Status: ${{ job.status }}
         Repository: ${{ github.repository }}
         Run ID: ${{ github.run_id }}
         Timestamp: $(date)
