name: "🧠 Auto Chat Memory Backup"

on:
  schedule:
    - cron: "0 * * * *"   # Runs every hour
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      - name: 💾 Commit chat memory backup
        run: |
          echo "Backing up chat memory..." > chat-memory.json
          git config --local user.email "records.8bfr.music.network@gmail.com"
          git config --local user.name "8BFR Backup Bot"
          git add chat-memory.json
          git commit -m "🧠 Auto backup chat memory [$(date)]" || echo "No changes to commit"
          git push

      - name: 📧 Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          secure: false
          username: ${{ secrets.SENDGRID_USER }}
          password: ${{ secrets.SENDGRID_PASS }}
          subject: "🧠 8BFR Backup Status: ${{ job.status }}"
          to: "records.8bfr.music.network@gmail.com"
          from: "8BFR Backup Bot <records@8bfr.music.network>"
          body: |
            Backup Job: ${{ github.workflow }}
            Status: ${{ job.status }}
            Repository: ${{ github.repository }}
            Run ID: ${{ github.run_id }}
            Timestamp: $(date)
