name: 🔁 Auto Backup Chat Memory

on:
  schedule:
    - cron: "*/10 * * * *"   # Runs every 10 minutes
  workflow_dispatch:          # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🕓 Set up timestamp
        id: timestamp
        run: echo "NOW=$(date -u +'%Y-%m-%dT%H-%M-%SZ')" >> $GITHUB_ENV

      - name: 📂 Create backup directory if missing
        run: mkdir -p backups

      - name: 🧠 Copy chat-memory.json to backups
        run: cp chat-memory.json backups/chat-backup-${{ env.NOW }}.json

      - name: 💾 Commit backup
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add backups/
          git commit -m "🧠 Auto backup chat memory (${{ env.NOW }})" || echo "No changes to commit"
          git push
