- name: Send memory backup email via SendGrid
  uses: dawidd6/action-send-mail@v3
  with:
    server_address: ${{ secrets.SENDGRID_SMTP_SERVER }}
    server_port: ${{ secrets.SENDGRID_SMTP_PORT }}
    username: ${{ secrets.SENDGRID_USER }}
    password: ${{ secrets.SENDGRID_PASS }}
    subject: "🧠 8BFR Memory Backup - ${{ github.run_id }}"
    to: ${{ secrets.SENDGRID_TO }}
    from: ${{ secrets.SENDGRID_FROM }}
    secure: true
    body: "Attached is the latest 8BFR project memory backup."
    attachments: chat-memory.json
